---
- name: "Customize Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-system"
    - role: "roles/customize-browser"
    - role: "roles/configure-terminator"
    - role: "roles/configure-nvim"
    - role: "gantsign.visual-studio-code"
      users:
      - username: "{{ ansible_user_id }}" 
        visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - GitHub.copilot
