---
- name: Create git folder if it does not exist
  file:
    path: /home/{{ ansible_user_id }}/git
    state: directory

- name: Get Neovim from Github
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: /home/{{ ansible_user_id }}/git/neovim

- name: Build neovim
  make:
    chdir: /home/{{ ansible_user_id }}/git/neovim
    params:
      CMAKE_BUILD_TYPE=RelWithDebInfo

- name: Run make install
  make:
    chdir: /home/{{ ansible_user_id }}/git/neovim
    target: install
  become: true

- name: "Copy config folder"
  copy:
    src: nvim
    dest: /home/{{ ansible_user_id }}/.config/

- name: "Copy config folder ROOT"
  copy:
    src: nvim
    dest: /root/.config/
  become: true

- name: "Install Packer"
  shell: git clone --depth 1 https://github.com/wbthomason/packer.nvim /home/{{ ansible_user_id }}/.local/share/nvim/site/pack/packer/start/packer.nvim
  ignore_errors: true

- name: "Install Packer ROOT"
  shell: git clone --depth 1 https://github.com/wbthomason/packer.nvim /root/.local/share/nvim/site/pack/packer/start/packer.nvim
  ignore_errors: true
  become: true

- name: "Install pyright language-server"
  npm:
    name: pyright
    global: true
  become: true
