---
- name: Reduce grub timeout
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=1'
  register: grub_timeout

- name: Update-grub
  become: true
  ansible.builtin.command: update-grub
  when: grub_timeout is changed
